name: Process-PSModule

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  Process-PSModule:
    uses: PSModule/Actions/.github/workflows/Process-PSModule.yml@main
    secrets: inherit
    with:
      TestModuleErrorAction: 'Continue'
      TestSrcErrorAction: 'Continue'
      Version: '0.0.157'
